//FOR USER
###
GET http://localhost:5000/user
###
POST http://localhost:5000/user
Content-Type: application/json

{
    "name" : "admintest",
    "email" : "admintest20@gmail.com"
}
###
GET http://localhost:5000/user/98081337-22a9-45df-98d0-6519946cf5eb
###
PUT http://localhost:5000/user/98081337-22a9-45df-98d0-6519946cf5eb
Content-Type: application/json

{
     "name" : "admintest10",
     "email" : "admintest10@gmail.com"
}

// error response
###
GET http://localhost:5000/euabdua
###
GET http://localhost:5000/user/98081337-22a9-45df-98d0-6519946cf533
###
PUT http://localhost:5000/user/98081337-22a9-45df-98d0-6519946cf533
Content-Type: application/json

{
     "name" : "admintest10",
     "email" : "admintest10@gmail.com"
}

// FOR Device
###
GET http://localhost:5000/device
###
GET http://localhost:5000/device/fcda7007-e772-4bf3-8e9e-926c772db38d
###
POST http://localhost:5000/device
Content-Type: application/json

{
    "title" : "Lampu Taman",
    "description" : "Kamar",
    "category" : "Switch",
    "value_number": 1,
    "value_boolean": true,
    "value_string" : "ON",
    "authorEmail" : "admintest20@gmail.com"
}
###
PUT http://localhost:5000/device/fcda7007-e772-4bf3-8e9e-926c772db38d
Content-Type: application/json

{
    "title" : "Lampu Kamar",
    "description" : "Kamar",
    "value" : "ON",
    "authorEmail" : "manutama10@gmail.com"
}

// Cyclcing app 

// device
### 
GET https://blue-violet-bighorn-sheep-boot.cyclic.app/device
### 
GET https://blue-violet-bighorn-sheep-boot.cyclic.app/user/191e117d-cbdf-40bc-9645-933d2160770a
###
GET https://blue-violet-bighorn-sheep-boot.cyclic.app/user
###
// user 
GET https://blue-violet-bighorn-sheep-boot.cyclic.app/user/275e4e51-cb43-4214-ab46-b73af937355b
###
POST https://blue-violet-bighorn-sheep-boot.cyclic.app/user
Content-Type: application/json

{
    "name" : "manutama",
    "email" : "adityavez10@gmail.com"
}
###
PUT https://blue-violet-bighorn-sheep-boot.cyclic.app/device/ca36d919-70b1-47a9-9ee5-10ce91783579
Content-Type: application/json

{
    "title" : "Lampu Taman",
    "description" : "Kamar",
    "category" : "Switch",
    "value_number": 19,
    "value_boolean": true,
    "value_string" : "ON",
    "authorEmail" : "admintest20@gmail.com"
}

###
POST https://blue-violet-bighorn-sheep-boot.cyclic.app/device
Content-Type: application/json

{
    "title" : "Lampu Taman",
    "description" : "Kamar",
    "category" : "Switch",
    "value_number": 19,
    "value_boolean": true,
    "value_string" : "ON",
    "authorEmail" : "adityavez10@gmail.com"
}
