apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
        - name: iot
          image: iot/backend
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: iot-srv
spec:
  type: NodePort
  selector:
    app: iot
  ports:
    - name: iot
      protocol: TCP
      port: 5000
      targetPort: 5000
